/**
 * University campuses with geocoded coordinates.
 *
 * Campus grain is deliberate: İTÜ Ayazağa and İTÜ Maçka are ~10 km apart, so a
 * single per-university coordinate would make proximity meaningless. Scores are
 * computed per campus and rolled up to the university by best campus.
 *
 * Generated by scripts/geo-refresh.js; `precision` is Google's location_type.
 * APPROXIMATE rows resolved only to neighbourhood level (~500 m).
 */

export interface Campus {
  /** Row from the CRM `universities` table. */
  campusName: string;
  /** Parent school in `university_canonical`. */
  canonicalName: string;
  lat: number;
  lng: number;
  precision: string;
}

export const CAMPUSES: Campus[] = [
  { campusName: "Acıbadem Üniversitesi", canonicalName: "Acıbadem Üniversitesi", lat: 40.978447, lng: 29.1102595, precision: "ROOFTOP" },
  { campusName: "Altınbaş Üniversitesi - Bakırköy", canonicalName: "Altınbaş Üniversitesi", lat: 40.9831153, lng: 28.8723442, precision: "ROOFTOP" },
  { campusName: "Altınbaş Üniversitesi - Esentepe", canonicalName: "Altınbaş Üniversitesi", lat: 41.0699029, lng: 29.012904, precision: "ROOFTOP" },
  { campusName: "Altınbaş Üniversitesi - Mahmutbey", canonicalName: "Altınbaş Üniversitesi", lat: 41.057263, lng: 28.82036849999999, precision: "ROOFTOP" },
  { campusName: "Ataşehir Adıgüzel MYO", canonicalName: "Ataşehir Adıgüzel MYO", lat: 40.9955429, lng: 29.1424024, precision: "GEOMETRIC_CENTER" },
  { campusName: "Bahçeşehir Üniversitesi", canonicalName: "Bahçeşehir Üniversitesi", lat: 41.042165, lng: 29.0092591, precision: "GEOMETRIC_CENTER" },
  { campusName: "Bahçeşehir Üniversitesi - Future Campus", canonicalName: "Bahçeşehir Üniversitesi", lat: 41.1598821, lng: 28.8963298, precision: "PLACES" },
  { campusName: "Bahçeşehir Üniversitesi - Göztepe", canonicalName: "Bahçeşehir Üniversitesi", lat: 40.9895083, lng: 29.0793038, precision: "PLACES" },
  { campusName: "Beykent Üniversitesi - Ayazağa", canonicalName: "Beykent Üniversitesi", lat: 41.117278, lng: 29.003757, precision: "ROOFTOP" },
  { campusName: "Beykent Üniversitesi - Taksim", canonicalName: "Beykent Üniversitesi", lat: 41.117278, lng: 29.003757, precision: "ROOFTOP" },
  { campusName: "Beykoz Üniversitesi", canonicalName: "Beykoz Üniversitesi", lat: 41.095822, lng: 29.09205, precision: "ROOFTOP" },
  { campusName: "Bezmialem Vakıf Üniversitesi", canonicalName: "Bezmialem Vakıf Üniversitesi", lat: 41.0188294, lng: 28.9350771, precision: "GEOMETRIC_CENTER" },
  { campusName: "Biruni Üniversitesi", canonicalName: "Biruni Üniversitesi", lat: 41.0178922, lng: 28.9164256, precision: "ROOFTOP" },
  { campusName: "Boğaziçi - Ana Kampüs", canonicalName: "Boğaziçi Üniversitesi", lat: 41.0836151, lng: 29.0517642, precision: "GEOMETRIC_CENTER" },
  { campusName: "Boğaziçi - Anadolu Hisarı", canonicalName: "Boğaziçi Üniversitesi", lat: 41.0810732, lng: 29.0690608, precision: "GEOMETRIC_CENTER" },
  { campusName: "Demiroğlu Bilim Üniversitesi - Gayrettepe", canonicalName: "Demiroğlu Bilim Üniversitesi", lat: 41.0691102, lng: 29.0123566, precision: "ROOFTOP" },
  { campusName: "Demiroğlu Bilim Üniversitesi - Silivri", canonicalName: "Demiroğlu Bilim Üniversitesi", lat: 41.0674649, lng: 28.3071988, precision: "ROOFTOP" },
  { campusName: "Doğuş Üniversitesi Çengelköy", canonicalName: "Doğuş Üniversitesi", lat: 41.0473104, lng: 29.0768992, precision: "ROOFTOP" },
  { campusName: "Doğuş Üniversitesi Dudullu", canonicalName: "Doğuş Üniversitesi", lat: 41.001717, lng: 29.176089, precision: "ROOFTOP" },
  { campusName: "Fatih Sultan Mehmet - Beyoğlu", canonicalName: "Fatih Sultan Mehmet Vakıf Üniversitesi", lat: 41.04633560000001, lng: 28.9432943, precision: "ROOFTOP" },
  { campusName: "Fatih Sultan Mehmet - Fatih", canonicalName: "Fatih Sultan Mehmet Vakıf Üniversitesi", lat: 41.0059261, lng: 28.9558872, precision: "ROOFTOP" },
  { campusName: "Fatih Sultan Mehmet - Üsküdar", canonicalName: "Fatih Sultan Mehmet Vakıf Üniversitesi", lat: 41.018606, lng: 29.022363, precision: "PLACES" },
  { campusName: "Fenerbahçe Üniversitesi", canonicalName: "Fenerbahçe Üniversitesi", lat: 40.99419410000001, lng: 29.121061, precision: "GEOMETRIC_CENTER" },
  { campusName: "Galatasaray Üniversitesi", canonicalName: "Galatasaray Üniversitesi", lat: 41.0459897, lng: 29.0198998, precision: "ROOFTOP" },
  { campusName: "Haliç Üniversitesi", canonicalName: "Haliç Üniversitesi", lat: 41.0858518, lng: 28.9521866, precision: "ROOFTOP" },
  { campusName: "İbn Haldun Üniversitesi", canonicalName: "İbn Haldun Üniversitesi", lat: 41.1380494, lng: 28.7958172, precision: "GEOMETRIC_CENTER" },
  { campusName: "Işık Üniversitesi - Maslak", canonicalName: "Işık Üniversitesi", lat: 41.1113574, lng: 29.0254502, precision: "GEOMETRIC_CENTER" },
  { campusName: "Işık Üniversitesi - Şile", canonicalName: "Işık Üniversitesi", lat: 41.16889949999999, lng: 29.5639972, precision: "GEOMETRIC_CENTER" },
  { campusName: "29 Mayıs Üniversitesi", canonicalName: "İstanbul 29 Mayıs Üniversitesi", lat: 41.0323125, lng: 29.098979, precision: "GEOMETRIC_CENTER" },
  { campusName: "Arel Üniversitesi - Büyükçekmece", canonicalName: "İstanbul Arel Üniversitesi", lat: 41.0552084, lng: 28.5002378, precision: "ROOFTOP" },
  { campusName: "Arel Üniversitesi - Cevizlibağ", canonicalName: "İstanbul Arel Üniversitesi", lat: 41.0172088, lng: 28.9137279, precision: "ROOFTOP" },
  { campusName: "Arel Üniversitesi - Sefaköy", canonicalName: "İstanbul Arel Üniversitesi", lat: 40.9991895, lng: 28.7959311, precision: "ROOFTOP" },
  { campusName: "Atlas Üniversitesi", canonicalName: "İstanbul Atlas Üniversitesi", lat: 41.0980536, lng: 28.9787565, precision: "ROOFTOP" },
  { campusName: "İstanbul Aydın Üniversitesi", canonicalName: "İstanbul Aydın Üniversitesi", lat: 40.9905166, lng: 28.7971611, precision: "ROOFTOP" },
  { campusName: "Bilgi Üniversitesi - Dolapdere", canonicalName: "İstanbul Bilgi Üniversitesi", lat: 41.0399775, lng: 28.9741723, precision: "ROOFTOP" },
  { campusName: "Bilgi Üniversitesi - Kuştepe", canonicalName: "İstanbul Bilgi Üniversitesi", lat: 41.0730626, lng: 28.9914096, precision: "ROOFTOP" },
  { campusName: "Bilgi Üniversitesi - Santralistanbul", canonicalName: "İstanbul Bilgi Üniversitesi", lat: 41.06607, lng: 28.94688, precision: "GEOMETRIC_CENTER" },
  { campusName: "Esenyurt Üniversitesi", canonicalName: "İstanbul Esenyurt Üniversitesi", lat: 41.0204138, lng: 28.6870992, precision: "ROOFTOP" },
  { campusName: "Galata Üniversitesi", canonicalName: "İstanbul Galata Üniversitesi", lat: 41.029577, lng: 28.97284, precision: "ROOFTOP" },
  { campusName: "İstanbul Galata Üniversitesi", canonicalName: "İstanbul Galata Üniversitesi", lat: 41.029577, lng: 28.97284, precision: "ROOFTOP" },
  { campusName: "Gelişim Üniversitesi", canonicalName: "İstanbul Gelişim Üniversitesi", lat: 40.9980215, lng: 28.698976, precision: "ROOFTOP" },
  { campusName: "Kent Üniversitesi - Kağıthane", canonicalName: "İstanbul Kent Üniversitesi", lat: 41.0856353, lng: 28.98045179999999, precision: "ROOFTOP" },
  { campusName: "Kent Üniversitesi - Taksim", canonicalName: "İstanbul Kent Üniversitesi", lat: 41.0334328, lng: 28.9840334, precision: "ROOFTOP" },
  { campusName: "Kültür Üniversitesi", canonicalName: "İstanbul Kültür Üniversitesi", lat: 40.9912928, lng: 28.8321354, precision: "GEOMETRIC_CENTER" },
  { campusName: "Medeniyet Üniversitesi - Güney", canonicalName: "İstanbul Medeniyet Üniversitesi", lat: 40.9957998, lng: 29.0635615, precision: "GEOMETRIC_CENTER" },
  { campusName: "Medeniyet Üniversitesi - Kuzey", canonicalName: "İstanbul Medeniyet Üniversitesi", lat: 40.9949988, lng: 29.0705991, precision: "ROOFTOP" },
  { campusName: "Medipol Üniversitesi - Güney", canonicalName: "İstanbul Medipol Üniversitesi", lat: 41.0884437, lng: 29.0888647, precision: "ROOFTOP" },
  { campusName: "Medipol Üniversitesi - Kuzey", canonicalName: "İstanbul Medipol Üniversitesi", lat: 41.0910745, lng: 29.0923411, precision: "GEOMETRIC_CENTER" },
  { campusName: "Nişantaşı Üniversitesi - Maslak 1453", canonicalName: "İstanbul Nişantaşı Üniversitesi", lat: 41.1194229, lng: 29.0089683, precision: "GEOMETRIC_CENTER" },
  { campusName: "Nişantaşı Üniversitesi - Nişantaşı", canonicalName: "İstanbul Nişantaşı Üniversitesi", lat: 41.0494637, lng: 28.9920183, precision: "VERIFIED-MANUAL" },
  { campusName: "Okan Üniversitesi", canonicalName: "İstanbul Okan Üniversitesi", lat: 40.951848, lng: 29.3921173, precision: "GEOMETRIC_CENTER" },
  { campusName: "İstanbul Rumeli Üniversitesi - Silivri", canonicalName: "İstanbul Rumeli Üniversitesi", lat: 41.0787145, lng: 28.2700921, precision: "ROOFTOP" },
  { campusName: "İTÜ - Ayazağa", canonicalName: "İstanbul Teknik Üniversitesi", lat: 41.1022431, lng: 29.0200389, precision: "GEOMETRIC_CENTER" },
  { campusName: "İTÜ - Maçka", canonicalName: "İstanbul Teknik Üniversitesi", lat: 41.045884, lng: 28.9959116, precision: "VERIFIED-MANUAL" },
  { campusName: "Ticaret Üniversitesi - Küçükyalı", canonicalName: "İstanbul Ticaret Üniversitesi", lat: 40.952899, lng: 29.1196104, precision: "ROOFTOP" },
  { campusName: "Topkapı Üniversitesi - Fatih", canonicalName: "İstanbul Topkapı Üniversitesi", lat: 41.0380477, lng: 28.9447553, precision: "ROOFTOP" },
  { campusName: "Topkapı Üniversitesi - Merter", canonicalName: "İstanbul Topkapı Üniversitesi", lat: 40.9951813, lng: 28.9176085, precision: "ROOFTOP" },
  { campusName: "İstanbul Üniversitesi", canonicalName: "İstanbul Üniversitesi", lat: 41.0126037, lng: 28.961838, precision: "GEOMETRIC_CENTER" },
  { campusName: "İstanbul Üniversitesi-Cerrahpaşa Cerrahpaşa Tıp Fakültesi", canonicalName: "İstanbul Üniversitesi-Cerrahpaşa (Tıp)", lat: 41.0062408, lng: 28.9399829, precision: "ROOFTOP" },
  { campusName: "İstanbul Üniversitesi-Cerrahpaşa Avcılar Kampüsü", canonicalName: "İstanbul Üniversitesi-Cerrahpaşa (Avcılar)", lat: 40.9886194, lng: 28.7226803, precision: "GEOMETRIC_CENTER" },
  { campusName: "Yeni Yüzyıl Üniversitesi", canonicalName: "İstanbul Yeni Yüzyıl Üniversitesi", lat: 41.0163922, lng: 28.90660969999999, precision: "PLACES" },
  { campusName: "İstinye Üniversitesi - Cevizlibağ", canonicalName: "İstinye Üniversitesi", lat: 41.0162006, lng: 28.909088, precision: "ROOFTOP" },
  { campusName: "İstinye Üniversitesi - Vadi", canonicalName: "İstinye Üniversitesi", lat: 41.1052707, lng: 28.9858336, precision: "ROOFTOP" },
  { campusName: "Kadir Has Üniversitesi", canonicalName: "Kadir Has Üniversitesi", lat: 41.0239369, lng: 28.959989, precision: "GEOMETRIC_CENTER" },
  { campusName: "Koç Üniversitesi", canonicalName: "Koç Üniversitesi", lat: 41.2084405, lng: 29.0749535, precision: "GEOMETRIC_CENTER" },
  { campusName: "Maltepe Üniversitesi", canonicalName: "Maltepe Üniversitesi", lat: 40.961244, lng: 29.19174439999999, precision: "GEOMETRIC_CENTER" },
  { campusName: "Marmara Üniversitesi - Göztepe", canonicalName: "Marmara Üniversitesi", lat: 40.9852209, lng: 29.0526574, precision: "PLACES" },
  { campusName: "Marmara Üniversitesi - Maltepe", canonicalName: "Marmara Üniversitesi", lat: 40.9590301, lng: 29.1353559, precision: "ROOFTOP" },
  { campusName: "MEF Üniversitesi - Maslak", canonicalName: "MEF Üniversitesi", lat: 41.1088445, lng: 29.0085964, precision: "ROOFTOP" },
  { campusName: "MSGSÜ - Beşiktaş", canonicalName: "Mimar Sinan Güzel Sanatlar Üniversitesi", lat: 41.042319, lng: 29.0085684, precision: "ROOFTOP" },
  { campusName: "MSGSÜ - Bomonti", canonicalName: "Mimar Sinan Güzel Sanatlar Üniversitesi", lat: 41.0576968, lng: 28.9800883, precision: "ROOFTOP" },
  { campusName: "Özyeğin Üniversitesi", canonicalName: "Özyeğin Üniversitesi", lat: 41.0310794, lng: 29.2577597, precision: "ROOFTOP" },
  { campusName: "Piri Reis Üniversitesi", canonicalName: "Piri Reis Üniversitesi", lat: 40.8149217, lng: 29.2903946, precision: "ROOFTOP" },
  { campusName: "Sabancı Üniversitesi", canonicalName: "Sabancı Üniversitesi", lat: 40.8924395, lng: 29.3772177, precision: "GEOMETRIC_CENTER" },
  { campusName: "Sağlık Bilimleri Üniversitesi", canonicalName: "Sağlık Bilimleri Üniversitesi", lat: 41.0044719, lng: 29.0212792, precision: "ROOFTOP" },
  { campusName: "Sağlık ve Sosyal Bilimler MYO", canonicalName: "Sağlık ve Sosyal Bilimler MYO", lat: 41.0062551, lng: 28.9848812, precision: "ROOFTOP" },
  { campusName: "Şişli MYO", canonicalName: "Şişli MYO", lat: 41.067919, lng: 29.0092131, precision: "ROOFTOP" },
  { campusName: "Üsküdar Üniversitesi", canonicalName: "Üsküdar Üniversitesi", lat: 41.0249642, lng: 29.0388276, precision: "ROOFTOP" },
  { campusName: "Yeditepe Üniversitesi", canonicalName: "Yeditepe Üniversitesi", lat: 40.97483889999999, lng: 29.1533709, precision: "ROOFTOP" },
  { campusName: "YTÜ - Beşiktaş", canonicalName: "Yıldız Teknik Üniversitesi", lat: 41.0521271, lng: 29.0108927, precision: "GEOMETRIC_CENTER" },
  { campusName: "YTÜ - Davutpaşa", canonicalName: "Yıldız Teknik Üniversitesi", lat: 41.0246296, lng: 28.8915915, precision: "GEOMETRIC_CENTER" },
  { campusName: "Ticaret Üniversitesi - Sütlüce", canonicalName: "İstanbul Ticaret Üniversitesi", lat: 41.05767, lng: 28.95083, precision: "PLACES" },
  { campusName: "İstanbul Sağlık ve Teknoloji Üniversitesi - Sütlüce", canonicalName: "İstanbul Sağlık ve Teknoloji Üniversitesi", lat: 41.05625, lng: 28.95107, precision: "PLACES" },
];
